model_name: "EleutherAI/gpt-neo-1.3B"
use_accelerate_device_map: True
load_in_8bit: False
device: 'cuda'
max_steps: 25
random_seed: 0
scoring_batch_size: 4
score_function: 'sum'
scoring_mode: 'guidance'  # naive, reuse_prompt, guidance
use_predefined_prompt: False  # NOTE: This uses a pre-defined prompt, and you can put a failure message in the prompt.
hf_auth_token: ''  # NOTE: this is required for downloading the private model from HuggingFace
openai_api_key: ''  # NOTE: this is required for using the OpenAI API
